/**
 * Emits supabase/seed/0002_metro_pumps.sql from packages/shared seed data so
 * the TS seed stays the single source of truth.
 * Run: node scripts/emit-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { SEED_PUMPS } from "../packages/shared/src/seed.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const rows = SEED_PUMPS
  // Pune pumps 1–8 are already in 0001_pune_pilot.sql
  .filter((p) => p.district !== "Pune")
  .map(
    (p) =>
      `  (${q(p.id)}, ${q(p.omc)}, ${q(p.dealerCode)}, ${q(p.name)}, ${q(p.address)}, ` +
      `${q(p.district)}, ${q(p.state)}, st_setsrid(st_makepoint(${p.lng}, ${p.lat}), 4326)::geography, ` +
      `'${JSON.stringify(p.blends)}', 'active')`,
  );

const sql = `-- Metro-city placeholder pumps (generated by scripts/emit-seed-sql.ts —
-- edit packages/shared/src/seed.ts and re-run instead of editing this file).
-- Replace with the OMC locator dataset before public launch.

insert into pumps (id, omc, dealer_code, name, address, district, state, location, blends, status) values
${rows.join(",\n")}
on conflict (id) do nothing;

insert into pump_scores (pump_id) select id from pumps
on conflict (pump_id) do nothing;
`;

writeFileSync("supabase/seed/0002_metro_pumps.sql", sql);
console.log(`wrote ${rows.length} pumps to supabase/seed/0002_metro_pumps.sql`);
